- module(growing_duration, []).

growing_duration("patthalung","indirect_seeding",103).
growing_duration("phitsanulok2","indirect_seeding",119).
growing_duration("phitsanulok60_2","indirect_seeding",130).
growing_duration("suphanburi1","indirect_seeding",120).
growing_duration("suphanburi2","indirect_seeding",115).
growing_duration("suphanburi3","indirect_seeding",115).
growing_duration("suphanburi60","indirect_seeding",120).
growing_duration("suphanburi90","indirect_seeding",120).
growing_duration("surin1","indirect_seeding",138).
growing_duration("rd5","indirect_seeding",140).
growing_duration("rd13","indirect_seeding",120).
growing_duration("rd15","indirect_seeding",147).
growing_duration("rd27","indirect_seeding",154).
growing_duration("rd35","indirect_seeding",120).
growing_duration("rd51","indirect_seeding",90).
growing_duration("rd59","indirect_seeding",133).
growing_duration("gowruang88","indirect_seeding",135).
growing_duration("jasmine105","indirect_seeding",150).
growing_duration("hawmmalidang","indirect_seeding",150).
growing_duration("khaotahhaeng17","indirect_seeding",135).
growing_duration("khaopahkmaw148","indirect_seeding",120).
growing_duration("khaojowhawmphitsanulok1","indirect_seeding",150).
growing_duration("rd23","indirect_seeding",125).
growing_duration("rd25","indirect_seeding",90).
growing_duration("rd29","indirect_seeding",99).
growing_duration("rd31","indirect_seeding",118).
growing_duration("rd33","indirect_seeding",130).
growing_duration("rd37","indirect_seeding",118).
growing_duration("rd39","indirect_seeding",125).
growing_duration("rd41","indirect_seeding",105).
growing_duration("rd43","indirect_seeding",90).
growing_duration("rd47","indirect_seeding",112).
growing_duration("rd49","indirect_seeding",97).
growing_duration("rd53","indirect_seeding",133).
growing_duration("rd55","indirect_seeding",117).
growing_duration("rd57","indirect_seeding",118).
growing_duration("rd61","indirect_seeding",85).
growing_duration("khaojowhawmsuphanburi","indirect_seeding",120).
growing_duration("chainat1","indirect_seeding",121).
growing_duration("chainat2","indirect_seeding",103).
growing_duration("rd6","indirect_seeding",120).
growing_duration("rd8","indirect_seeding",99).
growing_duration("nongkai80","indirect_seeding",110).
growing_duration("rd16","indirect_seeding",113).
growing_duration("rd18","indirect_seeding",116).
growing_duration("rd20","indirect_seeding",99).
growing_duration("hahngyu71","indirect_seeding",122).
growing_duration("mueynawng62m","indirect_seeding",120).
growing_duration("niawdammor37","indirect_seeding",140).
growing_duration("niawkiawngoo8974","indirect_seeding",120).
growing_duration("niawsan_pah_tawng","indirect_seeding",99).
growing_duration("niawubon1","indirect_seeding",92).
growing_duration("leuangpratew123","indirect_seeding",120).
growing_duration("ptnc96004_49","indirect_seeding",115).
growing_duration("rd2","indirect_seeding",130).
growing_duration("rd4","indirect_seeding",127).
growing_duration("rd14","indirect_seeding",136).
growing_duration("rd_maejo2","indirect_seeding",135).
growing_duration("phrae1","indirect_seeding",130).
growing_duration("sakonnakhon","indirect_seeding",128).
growing_duration("chiangphatthalung","indirect_seeding",126).
growing_duration("queen132","indirect_seeding",124).
growing_duration("ms_mons_4","indirect_seeding",134).
growing_duration("saguiwater19","indirect_seeding",127).
growing_duration("watertaro43","indirect_seeding",123).
growing_duration("pathumthani60","indirect_seeding",127).
growing_duration("puangrai2","indirect_seeding",137).
growing_duration("phattaling60","indirect_seeding",121).
growing_duration("phitsanulok3","indirect_seeding",123).
growing_duration("phitsanulok60_1","indirect_seeding",132).
growing_duration("phitsanulok80","indirect_seeding",122).
growing_duration("lookdaengpattani","indirect_seeding",121).
growing_duration("lebnokpattani","indirect_seeding",130).
growing_duration("ptnc09002_59","indirect_seeding",123).
growing_duration("leuangyai148","indirect_seeding",123).
growing_duration("khemtawngphatthalung","indirect_seeding",125).
growing_duration("khaoluangsan_pah_twang","indirect_seeding",123).
growing_duration("gaenjan","indirect_seeding",140).
growing_duration("pttc02019_1","indirect_seeding",126).
growing_duration("khaogawdiaw35","indirect_seeding",123).
growing_duration("cholung97","indirect_seeding",122).
growing_duration("khaimodrin3","indirect_seeding",137).
growing_duration("niawubon2","indirect_seeding",133).



growing_duration("patthalung","broadcast_sowing",112).
growing_duration("phitsanulok2","broadcast_sowing",124).
growing_duration("phitsanulok60_2","broadcast_sowing",135).
growing_duration("suphanburi1","broadcast_sowing",125).
growing_duration("suphanburi2","broadcast_sowing",120).
growing_duration("suphanburi3","broadcast_sowing",120).
growing_duration("suphanburi60","broadcast_sowing",125).
growing_duration("suphanburi90","broadcast_sowing",125).
growing_duration("surin1","broadcast_sowing",143).
growing_duration("rd5","broadcast_sowing",145).
growing_duration("rd13","broadcast_sowing",125).
growing_duration("rd15","broadcast_sowing",152).
growing_duration("rd27","broadcast_sowing",159).
growing_duration("rd35","broadcast_sowing",125).
growing_duration("rd51","broadcast_sowing",95).
growing_duration("rd59","broadcast_sowing",138).
growing_duration("gowruang88","broadcast_sowing",140).
growing_duration("jasmine105","broadcast_sowing",155).
growing_duration("hawmmalidang","broadcast_sowing",155).
growing_duration("khaotahhaeng17","broadcast_sowing",140).
growing_duration("khaopahkmaw148","broadcast_sowing",125).
growing_duration("khaojowhawmphitsanulok1","broadcast_sowing",155).
growing_duration("rd23","broadcast_sowing",130).
growing_duration("rd25","broadcast_sowing",100).
growing_duration("rd29","broadcast_sowing",104).
growing_duration("rd31","broadcast_sowing",111).
growing_duration("rd33","broadcast_sowing",135).
growing_duration("rd37","broadcast_sowing",108).
growing_duration("rd39","broadcast_sowing",130).
growing_duration("rd41","broadcast_sowing",110).
growing_duration("rd43","broadcast_sowing",95).
growing_duration("rd47","broadcast_sowing",104).
growing_duration("rd49","broadcast_sowing",102).
growing_duration("rd53","broadcast_sowing",138).
growing_duration("rd55","broadcast_sowing",104).
growing_duration("rd57","broadcast_sowing",108).
growing_duration("rd61","broadcast_sowing",90).
growing_duration("khaojowhawmsuphanburi","broadcast_sowing",125).
growing_duration("chainat1","broadcast_sowing",130).
growing_duration("chainat2","broadcast_sowing",105).
growing_duration("rd6","broadcast_sowing",125).
growing_duration("rd8","broadcast_sowing",104).
growing_duration("nongkai80","broadcast_sowing",115).
growing_duration("rd16","broadcast_sowing",118).
growing_duration("rd18","broadcast_sowing",121).
growing_duration("rd20","broadcast_sowing",104).
growing_duration("hahngyu71","broadcast_sowing",127).
growing_duration("mueynawng62m","broadcast_sowing",125).
growing_duration("niawdammor37","broadcast_sowing",145).
growing_duration("niawkiawngoo8974","broadcast_sowing",125).
growing_duration("niawsan_pah_tawng","broadcast_sowing",104).
growing_duration("niawubon1","broadcast_sowing",97).
growing_duration("leuangpratew123","broadcast_sowing",125).
growing_duration("ptnc96004_49","broadcast_sowing",120).
growing_duration("rd2","broadcast_sowing",135).
growing_duration("rd4","broadcast_sowing",132).
growing_duration("rd14","broadcast_sowing",141).
growing_duration("rd_maejo2","broadcast_sowing",140).
growing_duration("phrae1","broadcast_sowing",135).
growing_duration("sakonnakhon","broadcast_sowing",133).
growing_duration("chiangphatthalung","broadcast_sowing",131).
growing_duration("queen132","broadcast_sowing",129).
growing_duration("ms_mons_4","broadcast_sowing",139).
growing_duration("saguiwater19","broadcast_sowing",132).
growing_duration("watertaro43","broadcast_sowing",128).
growing_duration("pathumthani60","broadcast_sowing",132).
growing_duration("puangrai2","broadcast_sowing",142).
growing_duration("phattaling60","broadcast_sowing",126).
growing_duration("phitsanulok3","broadcast_sowing",128).
growing_duration("phitsanulok60_1","broadcast_sowing",137).
growing_duration("phitsanulok80","broadcast_sowing",127).
growing_duration("lookdaengpattani","broadcast_sowing",126).
growing_duration("lebnokpattani","broadcast_sowing",135).
growing_duration("ptnc09002_59","broadcast_sowing",128).
growing_duration("leuangyai148","broadcast_sowing",128).
growing_duration("khemtawngphatthalung","broadcast_sowing",130).
growing_duration("khaoluangsan_pah_twang","broadcast_sowing",128).
growing_duration("gaenjan","broadcast_sowing",145).
growing_duration("pttc02019_1","broadcast_sowing",131).
growing_duration("khaogawdiaw35","broadcast_sowing",128).
growing_duration("cholung97","broadcast_sowing",127).
growing_duration("khaimodrin3","broadcast_sowing",142).
growing_duration("niawubon2","broadcast_sowing",138).


growing_duration("patthalung","winter_period",127).
growing_duration("phitsanulok2","winter_period",139).
growing_duration("phitsanulok60_2","winter_period",150).
growing_duration("suphanburi1","winter_period",140).
growing_duration("suphanburi2","winter_period",135).
growing_duration("suphanburi3","winter_period",135).
growing_duration("suphanburi60","winter_period",140).
growing_duration("suphanburi90","winter_period",140).
growing_duration("surin1","winter_period",158).
growing_duration("rd5","winter_period",160).
growing_duration("rd13","winter_period",140).
growing_duration("rd15","winter_period",167).
growing_duration("rd27","winter_period",174).
growing_duration("rd35","winter_period",140).
growing_duration("rd51","winter_period",110).
growing_duration("rd59","winter_period",153).
growing_duration("gowruang88","winter_period",155).
growing_duration("jasmine105","winter_period",170).
growing_duration("hawmmalidang","winter_period",170).
growing_duration("khaotahhaeng17","winter_period",155).
growing_duration("khaopahkmaw148","winter_period",140).
growing_duration("khaojowhawmphitsanulok1","winter_period",170).
growing_duration("rd23","winter_period",145).
growing_duration("rd25","winter_period",115).
growing_duration("rd29","winter_period",103).
growing_duration("rd31","winter_period",126).
growing_duration("rd33","winter_period",150).
growing_duration("rd37","winter_period",123).
growing_duration("rd39","winter_period",145).
growing_duration("rd41","winter_period",125).
growing_duration("rd43","winter_period",110).
growing_duration("rd47","winter_period",119).
growing_duration("rd49","winter_period",117).
growing_duration("rd53","winter_period",153).
growing_duration("rd55","winter_period",119).
growing_duration("rd57","winter_period",123).
growing_duration("rd61","winter_period",105).
growing_duration("khaojowhawmsuphanburi","winter_period",130).
growing_duration("chainat1","winter_period",145).
growing_duration("chainat2","winter_period",120).
growing_duration("rd6","winter_period",140).
growing_duration("rd8","winter_period",103).
growing_duration("nongkai80","winter_period",130).
growing_duration("rd16","winter_period",133).
growing_duration("rd18","winter_period",136).
growing_duration("rd20","winter_period",119).
growing_duration("hahngyu71","winter_period",142).
growing_duration("mueynawng62m","winter_period",140).
growing_duration("niawdammor37","winter_period",160).
growing_duration("niawkiawngoo8974","winter_period",140).
growing_duration("niawsan_pah_tawng","winter_period",119).
growing_duration("niawubon1","winter_period",112).
growing_duration("leuangpratew123","winter_period",140).
growing_duration("ptnc96004_49","winter_period",135).
growing_duration("rd2","winter_period",150).
growing_duration("rd4","winter_period",147).
growing_duration("rd14","winter_period",156).
growing_duration("rd_maejo2","winter_period",155).
growing_duration("phrae1","winter_period",150).
growing_duration("sakonnakhon","winter_period",148).
growing_duration("chiangphatthalung","winter_period",146).
growing_duration("queen132","winter_period",144).
growing_duration("ms_mons_4","winter_period",154).
growing_duration("saguiwater19","winter_period",147).
growing_duration("watertaro43","winter_period",143).
growing_duration("pathumthani60","winter_period",147).
growing_duration("puangrai2","winter_period",157).
growing_duration("phattaling60","winter_period",141).
growing_duration("phitsanulok3","winter_period",143).
growing_duration("phitsanulok60_1","winter_period",152).
growing_duration("phitsanulok80","winter_period",142).
growing_duration("lookdaengpattani","winter_period",141).
growing_duration("lebnokpattani","winter_period",150).
growing_duration("ptnc09002_59","winter_period",143).
growing_duration("leuangyai148","winter_period",143).
growing_duration("khemtawngphatthalung","winter_period",145).
growing_duration("khaoluangsan_pah_twang","winter_period",143).
growing_duration("gaenjan","winter_period",160).
growing_duration("pttc02019_1","winter_period",146).
growing_duration("khaogawdiaw35","winter_period",143).
growing_duration("cholung97","winter_period",142).
growing_duration("khaimodrin3","winter_period",157).
growing_duration("niawubon2","winter_period",153).

growing_duration("rd7",_,150).
growing_duration("san_pah_tawng",_,150).