- module(photo_sensitive, []).

photo_sensitive("rd5").
photo_sensitive("rd13").
photo_sensitive("rd15").
photo_sensitive("rd27").
photo_sensitive("rd35").
photo_sensitive("rd51").
photo_sensitive("rd59").
photo_sensitive("gowruang88").
photo_sensitive("jasmine105").
photo_sensitive("hawmmalidang").
photo_sensitive("khaotahhaeng17").
photo_sensitive("khaopahkmaw148").
photo_sensitive("khaojowhawmphitsanulok1").
photo_sensitive("rd6").
photo_sensitive("rd8").
photo_sensitive("nongkai80").
photo_sensitive("rd16").
photo_sensitive("rd18").
photo_sensitive("rd20").
photo_sensitive("gampai15").
photo_sensitive("hahngyu71").
photo_sensitive("mueynawng62m").
photo_sensitive("niawdammor37").
photo_sensitive("niawkiawngoo8974").
photo_sensitive("niawsan_pah_tawng").
photo_sensitive("niawubon1").
photo_sensitive("leuangpratew123").
photo_sensitive("ptnc96004_49").
photo_sensitive("chiangphatthalung").
photo_sensitive("queen132").
photo_sensitive("ms_mons_4").
photo_sensitive("saguiwater19").
photo_sensitive("watertaro43").
photo_sensitive("pathumthani60").
photo_sensitive("puangrai2").
photo_sensitive("phattaling60").
photo_sensitive("phitsanulok3").
photo_sensitive("phitsanulok60_1").
photo_sensitive("phitsanulok80").
photo_sensitive("lookdaengpattani").
photo_sensitive("lebnokpattani").
photo_sensitive("ptnc09002_59").
photo_sensitive("leuangyai148").
photo_sensitive("khemtawngphatthalung").
photo_sensitive("khaoluangsan_pah_twang").
photo_sensitive("gaenjan").
photo_sensitive("pttc02019_1").
photo_sensitive("khaogawdiaw35").
photo_sensitive("cholung97").
photo_sensitive("khaimodrin3").
photo_sensitive("niawubon2").
