- module(rice, []).

rice("patthalung").
rice("phitsanulok2").
rice("phitsanulok60_2").
rice("suphanburi1").
rice("suphanburi2").
rice("suphanburi3").
rice("suphanburi60").
rice("suphanburi90").
rice("surin1").
rice("rd5").
rice("rd13").
rice("rd15").
rice("rd27").
rice("rd35").
rice("rd51").
rice("rd59").
rice("gowruang88").
rice("jasmine105").
rice("hawmmalidang").
rice("khaotahhaeng17").
rice("khaopahkmaw148").
rice("khaojowhawmphitsanulok1").
rice("rd23").
rice("rd25").
rice("rd29").
rice("rd31").
rice("rd33").
rice("rd37").
rice("rd39").
rice("rd41").
rice("rd43").
rice("rd47").
rice("rd49").
rice("rd53").
rice("rd55").
rice("rd57").
rice("rd61").
rice("rd63").
rice("khaojowhawmkhlongluang1").
rice("khaojowhawmsuphanburi").
rice("chainat1").
rice("chainat2").
rice("rd6").
rice("rd8").
rice("nongkai80").
rice("rd16").
rice("rd18").
rice("rd20").
rice("gampai15").
rice("hahngyu71").
rice("mueynawng62m").
rice("niawdammor37").
rice("niawkiawngoo8974").
rice("niawsan_pah_tawng").
rice("niawubon1").
rice("leuangpratew123").
rice("ptnc96004_49").
rice("rd2").
rice("rd4").
rice("rd14").
rice("rd_maejo2").
rice("phrae1").
rice("sakonnakhon").
rice("chiangphatthalung").
rice("queen132").
rice("ms_mons_4").
rice("saguiwater19").
rice("watertaro43").
rice("pathumthani60").
rice("puangrai2").
rice("phattaling60").
rice("phitsanulok3").
rice("phitsanulok60_1").
rice("phitsanulok80").
rice("lookdaengpattani").
rice("lebnokpattani").
rice("ptnc09002_59").
rice("leuangyai148").
rice("khemtawngphatthalung").
rice("khaoluangsan_pah_twang").
rice("gaenjan").
rice("pttc02019_1").
rice("khaogawdiaw35").
rice("cholung97").
rice("khaimodrin3").
rice("niawubon2").
